### ISSUE TITLE
Reach out to universities/colleges to conduct user research

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/sf-crime-data#27]
We need to understand what their user needs are, since PD is expected to send them to this web application instead of sending universities/colleges the data themselves.

**Comment by paulhennings** [comment]
We envision that our initial users are universities/colleges within the boundaries of SFPD. How/where can we keep this list and track our progress in making contact to gather user needs? Since the list may have specific person contact details, so we need to share that in a "non-open-source" place for privacy?

**Comment by hackajesse** [comment]
Got a conversation with Jason Heil of UCSF scheduled for 7/12. Otherwise, no dice yet. @paulhennings are you with us still?

**Comment by hackajesse** [comment]
Working on Boston folks for the Boston pilot: 
Dan O'Brien at Northeastern - dobrien@neu.edu. Copy Harlan's cfa address. Runs Boston Area Research Initiative. Intro Jesse as City person, too.
David Eaves at Harvard.
Eric Gordon at Emerson. 
Mike Ward at UMass Boston. Runs civic data. michael.ward@umb.edu. Copy Harlan.
Dan Greenwood (Dazza) at MIT Media Lab.

**Comment by paulhennings** [comment]
@hackajesse I am out of town July 5-8. I plan to attend Civic Hack Night Wednesday, July 13.
