### ISSUE TITLE
Add feedback loop

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#4]
Create simple form capture for feedback that comes back to the Brigade or invites folks to add issues to the repository (in the interim). Feedback should eventually go to a team that wants to make this better at the Brigade. So before that form exists, should probably get a place for it to go.

**Comment by bhuber2010** [comment]
Note to self: Public way to post to GitHub issues? Otherwise form posts to database or some open (non-login) request submittal service. Then create Admin Login button to direct to simple page to view feedback.

**Comment by paulhennings** [comment]
I want to receive an e-mail or a notification when feedback or questions are submitted, so that we can respond promptly to solve the users problem, build a relationship with the user and learn more about how users want the site to work. We need to gather users contact info and give responding users an opportunity to specify if they do not want to be contacted.

E-mail only would be a fine way to start. Kkeeping a history in a database would be nice to have also. I'm shy about automatically opening a GitHub issue from feedback, as "junk" feedback could clutter up our Issues area. If we went with opening an Issue, then I'd want the issue set with me (and others) as a subscriber, so we receive notifications on the new issue. Slack could be an option, but again, junk feedback could clutter the stream and break up team conversation. Team members who want notification of feedback would need to enable Slack notifications.

I lean toward our on-going site philosophy: Keep It SSimple.

**Comment by sarah-clements** [comment]
I'll take a stab at this @paulhennings
